---
version: 2
updates:
- package-ecosystem: gomod
  directory: "."
  schedule:
    interval: weekly
    day: monday
    time: '09:00'
  open-pull-requests-limit: 10
  assignees:
  - javiyt
  reviewers:
  - javiyt
  ignore:
  - dependency-name: "*"
    update-types:
    - version-update:semver-patch
- package-ecosystem: github-actions
  directory: ".github/workflows"
  schedule:
    interval: weekly
    day: monday
    time: '09:00'
  open-pull-requests-limit: 10
  assignees:
  - javiyt
  reviewers:
  - javiyt
  ignore:
  - dependency-name: "*"
    update-types:
    - version-update:semver-patch
