name: Sync Fork

on:
  #schedule:
    #- cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: dghubble
          base: master
          head: master
          merge_method: squash
          token: ${{ secrets.PERSONAL_TOKEN }}
